version: '3.8'

services:
  # Next.js 前端應用
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend
      - redis
    networks:
      - sandbox-network

  # Node.js 後端服務
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - USE_DOCKER=true
      - MAX_SANDBOXES=100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./sandboxes:/app/sandboxes
    depends_on:
      - redis
    networks:
      - sandbox-network

  # Redis 快取和會話管理
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - sandbox-network

  # Nginx 反向代理和負載均衡
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - sandbox-network

networks:
  sandbox-network:
    driver: bridge

volumes:
  redis-data: